-- Align ClaimType enum values with Phase 4 API contract.
ALTER TYPE "ClaimType" RENAME VALUE 'RETURN_REFUND' TO 'RETURN_REQUEST';
ALTER TYPE "ClaimType" RENAME VALUE 'WARRANTY_REPAIR' TO 'REFUND_REQUEST';
ALTER TYPE "ClaimType" RENAME VALUE 'WARRANTY_REPLACEMENT' TO 'WARRANTY_CLAIM';
